site_name: "Daily Market Briefings"
site_url: "https://kristiyankostadinov-eightcap.github.io/s1a2l3e4s5/"

theme:
  name: "material"

plugins:
  - search
  - awesome-pages

docs_dir: 'snapshots'

# --- THE FIX IS HERE ---
# This new section controls the Table of Contents depth.
markdown_extensions:
  - toc:
      # This tells the theme to only include h2 (##) and h3 (###) headings.
      # Since your asset names are h2, this will give you the clean list you want.
      permalink: true
      toc_depth: 2