site_name: "Daily Market Briefings"
site_url: "https://kristiyankostadinov-eightcap.github.io/s1a2l3e4s5/"

theme:
  name: "material"

plugins:
  - search
  - awesome-pages

docs_dir: 'snapshots'

# This section cleans up the right-hand "Table of contents"
markdown_extensions:
  - toc:
      permalink: true
      # This tells the theme to only include level 2 headings (##) in the table.
      # This will result in a clean list of just your asset names.
      toc_depth: 2