site_name: "Daily Market Briefings"
site_url: "https://kristiyankostadinov-eightcap.github.io/s1a2l3e4s5/"

theme:
  name: "material"

plugins:
  - search
  # This plugin will now automatically create a nested sidebar from your folder structure.
  - awesome-pages

# Tell MkDocs where to find all the content.
docs_dir: 'snapshots'