name: Generate and Deploy Daily Market Briefing

on:
  workflow_dispatch: # Allows manual triggering
  schedule:
    - cron: '30 5 * * *' # Runs every day at 05:30 UTC

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies and Browsers
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install chromium --with-deps

      - name: Run the Market Analysis Script
        env:
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
        run: python main.py

      - name: Build the MkDocs Website
        run: mkdocs build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site

      - name: Trigger Slack Workflow
        if: success()
        run: |
          TODAY_DATE=$(date +%Y-%m-%d)
          REPORT_URL="https://kristiyankostadinov-eightcap.github.io/s1a2l3e4s5/briefings/briefing_$TODAY_DATE/"
          JSON_PAYLOAD="{\"report_url\": \"$REPORT_URL\"}"
          curl -X POST -H 'Content-type: application/json' --data "$JSON_PAYLOAD" ${{ secrets.SLACK_WORKFLOW_URL }}
